# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3

# NOTE: The namespace sharing for a pod has been modified by the user and is not the same as the
# default settings for kubernetes. This can lead to unexpected behavior when running the generated
# kube yaml in a kubernetes cluster.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-05-04T12:15:02Z"
  labels:
    app: podmcmc-rs
  name: podmcmc-rs
spec:
  containers:
    - args:
        - memcached
      image: docker.io/library/memcached:alpine
      name: mcmc-rsmd-tcp01
      ports:
        - containerPort: 11211
          hostPort: 11211
      securityContext: {}
    - args:
        - -s
        - /tmp/memcached.sock
      image: docker.io/library/memcached:alpine
      name: mcmc-rsmd-unix01
      securityContext: {}
      volumeMounts:
        - mountPath: /tmp
          name: tmp-host-0
    - args:
        - -p
        - "11212"
        - -S
        - -Y
        - /app/sasl.txt
      image: docker.io/library/memcached:alpine
      name: mcmc-rsmd-tcp11
      ports:
        - containerPort: 11212
          hostPort: 11212
      securityContext: {}
      volumeMounts:
        - mountPath: /app/sasl.txt
          name: home-artem-projects-mcmc-rs-sasl.txt-host-0
          readOnly: true
    - args:
        - -p
        - "11213"
        - -A
      image: docker.io/library/memcached:alpine
      name: mcmc-rsmd-tcp21
      ports:
        - containerPort: 11213
          hostPort: 11213
      securityContext: {}
  volumes:
    - hostPath:
        path: sasl.txt
        type: File
      name: home-artem-projects-mcmc-rs-sasl.txt-host-0
    - hostPath:
        path: /tmp
        type: Directory
      name: tmp-host-0
