name: CI

on: [pull_request, push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: Run tests.
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Run servers
        run: |
          docker compose up -d
          bash chmod_unix.bash
      - name: Run tests
        run: |
          cargo test

  coverage:
    runs-on: "ubuntu-latest"
    name: Run tests coverage.
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run servers
        run: |
          docker compose up -d
          bash chmod_unix.bash
      - name: Run tests coverage
        run: |
          cargo llvm-cov --doctests

  bench:
    runs-on: "ubuntu-latest"
    name: Run benchmark.
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Run servers
        run: |
          docker compose up -d
          bash chmod_unix.bash
      - name: Run benchmark
        run: |
          cargo bench
